[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "src"
version = "0.0.0"

[tool.setuptools]
packages = ["src"]

[project.scripts]
setup-freesurfer = "src.utilities.setup_freesurfer:setup_freesurfer_environment"