* Notes by day
**  1-10-23    
- Loaded pycortex and set up github repo
- Currently stuck on importing subject to pycortex db
** 1-12-23
- Still stuck on importing subjects
- Command mri_convert IS running in terminal, something at issue with kernel?
     - FREESURFER_HOME is set  
     
- BUT when command runs in terminal, new error nibabel function get_affine is deprecated for .affine, change to pycortex breaks 
     - Changed pycortex code line 198 to include .affine, no change

** 1-17-23
SOLVED: needed to run SetUpFreesurfer inside of virtual environment
export FREESURFER_HOME=~/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

Add the two above lines to conda environment activate.d with the following 

cd $CONDA_PREFIX
mkdir -p ./etc/conda/activate.d
mkdir -p ./etc/conda/deactivate.d
touch ./etc/conda/activate.d/env_vars.sh
touch ./etc/conda/deactivate.d/env_vars.sh

edit this file ./etc/conda/activate.d/env_vars.sh :
export FREESURFER_HOME=~/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

NEXT:
Not runnning in the jupyter notebook CNL_scalpel_scratch.ipynb like equivalent code is running in pycortex_subject_test.pycortex
error is unrecognized command mri_convert
     - Implies that kernal is not finding SetUpFreesurfer.sh when kernel is activated in jupyter vs when environment active in terminal

OTHER ISSUE:
Still empty! /Users/benparker/miniconda3/envs/CNL_scalpel/share/pycortex/db/100307/anatomicals
Not sure if this needs to have files in it, but likely should after running import_subj
Raises question of whether the command is runnning correctly in terminal as well

** 1-20-23

Left pycortex import, not sure issue not worth it now

New strategy is using nibabel functions to pull boundary vertices from existing labels. Then use these labels as boundary lines, 
and take all vertices in brain with values between these.

Created inferior boundary function. 
     - TODO outliers within function
          - Currently function works by binning all vertices along a given axis -- in this case anterior -- and then getting vertex with minimum S values   
          in the bin. Issue is occasionally the lowest s value for a given bin is far from the true boundary.
          - possible solution: remove all vertices more than 3 sds from boundary
     - TODO use function to capture all vertices above the boundary sulcus
     - TODO Visualize interactively


* Issues 


* TODO
Potentially older version of freesurfer required